export type Language = "id" | "en";

export const translations = {
  id: {
    nav: { home: "Beranda", menu: "Menu", experience: "Pengalaman", location: "Lokasi", contact: "Kontak", main: "Navigasi utama", mobile: "Navigasi seluler", open: "Buka menu navigasi", language: "Pilihan bahasa", reserve: "Reservasi Meja", reserveWhatsapp: "Reservasi via WhatsApp" },
    hero: { eyebrow: "Selamat datang · Kota Baru Parahyangan", title1: "Rasa", title2: "Kelas Satu.", title3: "Tetap di Darat.", body: "Kedai kopi dan tempat makan bertema aviasi untuk sarapan, makan bersama, dan jeda yang terasa seperti perjalanan istimewa.", menu: "Lihat Menu Kami", flight: "Penerbangan", destination: "Tujuan", service: "Layanan", serviceValue: "BERSANTAP SEPANJANG HARI" },
    about: { eyebrow: "Selamat datang", intro: "Bukan sekadar tempat singgah. Flight 79 adalah tujuan untuk menikmati rasa, suasana, dan waktu bersama.", title1: "Satu destinasi untuk", title2: "kopi yang serius", title3: ", makanan yang akrab, dan pengalaman yang tak biasa.", body1: "Terinspirasi oleh rasa antusias sebelum perjalanan dimulai, kami memadukan hangatnya kedai kopi dengan detail ruang tunggu bandara yang modern dan elegan.", body2: "Datang untuk menikmati kopi sejenak, lalu tinggal lebih lama untuk makan bersama. Setiap kunjungan dirancang agar terasa ramah, nyaman, dan layak dikenang." },
    menu: { eyebrow: "Pilihan menu", title: "Menu Andalan", body: "Dari suapan pertama hingga hidangan penutup—pilihan rasa untuk setiap waktu dan setiap tamu.", full: "Lihat Menu Lengkap", note: "Foto digunakan sebagai visual kategori, bukan representasi setiap item. Lihat menu lengkap untuk pilihan dan informasi terbaru.", tabLabel: "Kategori menu Flight 79", category: "Kategori", visual: "Visual kategori", categoryLabels: { breakfast: "Sarapan & Makanan Ringan", mains: "Hidangan Utama", refreshers: "Minuman Segar", coffee: "Kopi", dessert: "Pencuci Mulut" }, noPhoto: "Foto belum tersedia", sweetFinish: "Penutup yang manis.", noPhotoBody: "Tidak semua pilihan memerlukan foto untuk tetap menggugah selera." },
    experience: { eyebrow: "Pengalaman Flight 79", title: "Setiap kunjungan adalah bagian dari perjalanan.", mood: "Suasana kabin", moodBody: "Premium, santai, dan bersahabat.", highlights: ["Sarapan", "Menu sepanjang hari", "Rombongan"], features: [{ title: "Suasana Aviasi", copy: "Detail landasan, label penerbangan, dan nuansa ruang tunggu hadir secara halus—unik untuk dinikmati, tetap hangat untuk ditempati." }, { title: "Pilihan Sepanjang Hari", copy: "Mulai dari croissant dan kopi spesial hingga pizza, pasta, hidangan Indonesia, steak, pencuci mulut, dan minuman segar." }, { title: "Nyaman untuk Bersama", copy: "Nyaman untuk sarapan, rapat, waktu bersama keluarga, perayaan, atau sekadar mengobrol panjang bersama teman." }] },
    gallery: { eyebrow: "Pemandangan dari kursi jendela", title: "Sekilas Suasana Kami", body: "Suasana, rasa, dan detail yang membuat setiap kunjungan terasa seperti destinasi baru.", items: ["Area duduk Flight 79 dengan mural peta dunia dan deretan lampu gantung", "Mesin espresso Flight 79 dengan secangkir kopi yang baru diseduh", "Area makan Flight 79 dengan tanaman rambat dan pencahayaan alami", "Koleksi miniatur pesawat yang memperkuat tema aviasi Flight 79", "Logo Flight 79 dengan iluminasi hangat pada dinding interior"] },
    location: { eyebrow: "Informasi kedatangan", title: "Destinasi rasa Anda berikutnya.", address: "Alamat", hours: "Jam operasional", parking: "Parkir", directions: "Lihat Petunjuk Arah", map: "Peta lokasi Flight 79" },
    reviews: { eyebrow: "Ulasan pelanggan", title: "Kata Para Tamu", body: "Baca pengalaman tamu langsung melalui profil resmi Flight 79 di Google Maps.", all: "Lihat Semua Ulasan", carousel: "Ulasan tamu Flight 79", selected: "Pilihan ulasan Google Maps", previous: "Ulasan sebelumnya", next: "Ulasan berikutnya", stars: "dari 5 bintang" },
    events: { eyebrow: "Acara istimewa", title: "Rencanakan Acara Anda", body: "Bawa orang-orang favorit Anda. Kami siap membantu menyiapkan suasana yang pas untuk momen penting.", cta: "Rencanakan Acara", carousel: "Pilihan suasana untuk acara di Flight 79", previous: "Foto acara sebelumnya", next: "Foto acara berikutnya", show: "Tampilkan foto", items: ["Perayaan ulang tahun", "Acara keluarga", "Pertemuan perusahaan", "Acara komunitas", "Pertemuan pencinta aviasi"], slides: [{ eyebrow: "Perayaan pribadi", title: "Ulang tahun & momen spesial" }, { eyebrow: "Bersama di satu meja", title: "Acara keluarga & komunitas" }, { eyebrow: "Pertemuan berkarakter", title: "Rapat & acara komunitas" }] },
    contact: { eyebrow: "Panggilan terakhir", title1: "Siap untuk", title2: "Berangkat?", body: "Reservasi meja untuk sarapan, makan bersama, rapat, atau perayaan. Isi detail di bawah dan lanjutkan lewat WhatsApp.", phone: "Telepon / WhatsApp", email: "Email", destination: "Lokasi" },
    form: { label: "Form reservasi Flight 79", name: "Nama", namePlaceholder: "Nama lengkap", whatsapp: "Nomor WhatsApp", date: "Tanggal", time: "Waktu", guests: "Jumlah tamu", request: "Permintaan khusus", requestPlaceholder: "Kursi anak, perayaan, area pilihan, atau informasi lain...", submit: "Kirim Reservasi via WhatsApp", success: "Detail reservasi sudah disiapkan. Lanjutkan pengiriman di WhatsApp." },
    footer: { homeLabel: "Flight 79 — kembali ke beranda", body: "Rasa kelas satu di setiap hidangan. Sebuah destinasi rasa dan suasana bertema aviasi di Kota Baru Parahyangan.", quick: "Tautan cepat", nav: "Navigasi bagian bawah", connected: "Tetap terhubung", rights: "Hak cipta dilindungi." },
  },
  en: {
    nav: { home: "Home", menu: "Menu", experience: "Experience", location: "Location", contact: "Contact", main: "Main navigation", mobile: "Mobile navigation", open: "Open navigation menu", language: "Language selector", reserve: "Reserve Your Seat", reserveWhatsapp: "Reserve via WhatsApp" },
    hero: { eyebrow: "Now boarding · Kota Baru Parahyangan", title1: "First-Class", title2: "Flavor.", title3: "On the Ground.", body: "An aviation-themed coffee & eatery for breakfast, shared meals, and breaks that feel like a special journey.", menu: "Explore Our Menu", flight: "Flight", destination: "Destination", service: "Service", serviceValue: "ALL DAY DINING" },
    about: { eyebrow: "Welcome aboard", intro: "More than a stopover. Flight 79 is a destination for enjoying great flavors, atmosphere, and time together.", title1: "One destination for", title2: "serious coffee", title3: ", familiar food, and an experience beyond the ordinary.", body1: "Inspired by the anticipation before a journey begins, we blend the warmth of a coffee house with modern, elegant airport-lounge details.", body2: "Come for a quick coffee, stay longer for a shared meal. Every visit is designed to feel welcoming, effortless, and memorable." },
    menu: { eyebrow: "In-flight selection", title: "Signature Flights", body: "From the first bite to a sweet landing—flavors for every moment and every passenger.", full: "View Full Menu", note: "Photos represent each category and may not depict every item. See the full menu for the latest selection and information.", tabLabel: "Flight 79 menu categories", category: "Category", visual: "Category visual", categoryLabels: { breakfast: "Breakfast & Light", mains: "Main Course", refreshers: "Refreshers", coffee: "Coffee", dessert: "Dessert" }, noPhoto: "No photograph available", sweetFinish: "A sweet finish.", noPhotoBody: "Not every selection needs a photograph to remain tempting." },
    experience: { eyebrow: "The Flight 79 experience", title: "Every visit is part of the journey.", mood: "Cabin mood", moodBody: "Premium, relaxed, welcoming.", highlights: ["Breakfast", "All-day menu", "Groups"], features: [{ title: "Aviation Atmosphere", copy: "Runway details, flight labels, and lounge-inspired touches appear subtly—distinctive to discover, yet warm enough to settle into." }, { title: "All-Day Choices", copy: "From croissants and specialty coffee to pizza, pasta, Indonesian favorites, steak, desserts, and refreshers." }, { title: "Made for Together", copy: "Comfortable for breakfast, meetings, family time, celebrations, or long conversations with friends." }] },
    gallery: { eyebrow: "Window seat view", title: "A Glimpse On Board", body: "The atmosphere, flavors, and details that make every visit feel like a new destination.", items: ["Flight 79 seating area with a world-map mural and pendant lights", "Flight 79 espresso machine with a freshly brewed cup of coffee", "Flight 79 dining area with trailing greenery and natural light", "Aircraft miniatures that bring Flight 79's aviation theme to life", "Flight 79 logo illuminated warmly on an interior wall"] },
    location: { eyebrow: "Arrival information", title: "Your next flavor destination.", address: "Address", hours: "Opening hours", parking: "Parking", directions: "Get Directions", map: "Flight 79 location map" },
    reviews: { eyebrow: "Passenger reviews", title: "What Our Guests Say", body: "Read real guest experiences from Flight 79's official Google Maps listing.", all: "View All Reviews", carousel: "Flight 79 guest reviews", selected: "Selected Google Maps review", previous: "Previous review", next: "Next review", stars: "out of 5 stars" },
    events: { eyebrow: "Special occasions", title: "Plan Your Event", body: "Bring your favorite people. We are ready to help create the right atmosphere for your important moments.", cta: "Plan Your Event", carousel: "Event settings at Flight 79", previous: "Previous event photo", next: "Next event photo", show: "Show photo", items: ["Birthday celebrations", "Family gatherings", "Corporate meetings", "Community gatherings", "Aviation enthusiast meetups"], slides: [{ eyebrow: "Private celebrations", title: "Birthdays & special moments" }, { eyebrow: "Together at the table", title: "Family & community gatherings" }, { eyebrow: "Meet with character", title: "Meetings & community events" }] },
    contact: { eyebrow: "Final call", title1: "Ready for", title2: "Take-Off?", body: "Reserve a table for breakfast, a shared meal, a meeting, or a celebration. Fill in the details below and continue via WhatsApp.", phone: "Phone / WhatsApp", email: "Email", destination: "Destination" },
    form: { label: "Flight 79 reservation form", name: "Name", namePlaceholder: "Full name", whatsapp: "WhatsApp number", date: "Date", time: "Time", guests: "Number of guests", request: "Special request", requestPlaceholder: "High chair, celebration, preferred area, or other information...", submit: "Send Reservation via WhatsApp", success: "Your reservation details are ready. Continue sending them in WhatsApp." },
    footer: { homeLabel: "Flight 79 — back to home", body: "First-class flavor on every plate. An aviation-themed destination for flavor and atmosphere in Kota Baru Parahyangan.", quick: "Quick links", nav: "Footer navigation", connected: "Stay connected", rights: "All rights reserved." },
  },
} as const;
